# See the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Infrastructure
  ## GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(ci)"

  # Codebase
  ## Go dependencies
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(go-tools)"

  ## Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(rust)"
